= ingress-nginx: A Commodore component to manage the NGINX Ingress Controller

ingress-nginx is a Commodore component to manage ingress-nginx.
The component is based on the official https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx[Helm Chart].

Check the https://kubernetes.github.io/ingress-nginx/[official documentation] for further information.

[CAUTION]
====
This component requires at least ArgoCD 1.8. Check the https://github.com/argoproj/argo-cd/issues/2737[issue].
====

[CAUTION]
====
This component requires a minimum Kubernetes version of 1.22.
====

See the xref:references/parameters.adoc[parameters] reference for further details.

== Add a default ingress TLS certificate

By default the NGINX Ingress Controller does create a fake certificate provided to clients connecting via HTTPS.
A specific TLS certificate can be provided on each ingress or a default certificate can be added provided, when no ingress specific certificate is available.

[source,yaml]
----
parameters:
  ingress_nginx:
    helm_values:
      controller:
        extraArgs:
          default-ssl-certificate: "syn-ingress-nginx/default-ingress-tls"
----
