= Parameters

The parent key for all of the following parameters is `ingress_nginx`.

== `namespace`

[horizontal]
type:: string
default:: `syn-ingress-nginx`

The namespace in which to deploy this component.


== `release_name`

[horizontal]
type:: string
default:: `ingress-nginx`

The name ingress-nginx is deployed.
Usually there is just one deployment and therefore no change is required.

== `kubernetes_version`

[horizontal]
type:: string
default:: `null`

The kubernetes version to be used.

== `chroot`

[horizontal]
type:: boolean
default:: `false`

Whether to enable the chrooted web proxy server.
Please see the xref:how-tos/enable-chroot.adoc[chroot how-to].


== `pod_security_admission`

[horizontal]
type:: dict
default::

[source,yaml]
----
pod_security_admission:
  enabled: true <1>
  enforce: privileged <2>
  audit: privileged <3>
  warn: privileged <4>
----
<1> Wether to set any Pod Security Admission labels
<2> Which Pod Security Standard to enforce in the created namespace
<3> Which Pod Security Standard to audit in the created namespace
<4> Which Pod Security Standard to warn on in the created namespace

The Pod Security Admission configuration.
Pod Security Admission can be enabled or disabled and which standard to enforce, warn, or audit on can be configured.

You can remove any of the label by setting the repecitive field to an empty string or `null`.

Please consult the https://kubernetes.io/docs/concepts/security/pod-security-admission/[upstream documentation].

NOTE: We default to enforce the `privileged` standard.
As of writing this the helm chart sets `allowPrivilegeEscalation: true`, which is only allowd for privileged workloads.
However, this is most likely not needed and if the upstream chart changes this default should be reevaluated.

== `charts.ingress-nginx`

[horizontal]
type:: string
default:: See `class/defaults.yml`


== `helm_values`

[horizontal]
type:: dict


All helm_values are passed to the helm chart.
This allows to configure all https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/values.yaml[ingress-nginx helm chart values].

[source,yaml]
----
parameters:
  ingress_nginx:
    helm_values:
      controller:
        config:
          hsts: 'false'
----
