parameters:
  kapitan:
    dependencies:
      - type: helm
        output_path: dependencies/ingress-nginx/helmcharts/ingress-nginx/${ingress_nginx:charts:ingress-nginx}/
        source: https://kubernetes.github.io/ingress-nginx
        version: ${ingress_nginx:charts:ingress-nginx}
        chart_name: ingress-nginx
    compile:
      - input_paths:
          - ingress-nginx/component/app.jsonnet
        input_type: jsonnet
        output_path: .
      - input_paths:
          - ingress-nginx/component/main.jsonnet
        input_type: jsonnet
        output_path: ingress-nginx/

      - input_type: helm
        output_path: ingress-nginx/10_ingress_nginx_helmchart
        input_paths:
          - ingress-nginx/helmcharts/ingress-nginx/${ingress_nginx:charts:ingress-nginx}/
        helm_values: ${ingress_nginx:helm_values}
        helm_params:
          name: ${ingress_nginx:release_name}
          namespace: ${ingress_nginx:namespace}
          kube_version: ${ingress_nginx:kubernetes_version}
  commodore:
    postprocess:
      filters:
        - type: jsonnet
          filter: postprocess/poddisruptionbudget.jsonnet
          path: ${_instance}/10_ingress_nginx_helmchart/ingress-nginx/templates
